import { Model, ObjectId, Schema, model, models } from 'mongoose';

export interface AutoGeneratedPlaylistDocument {
  title: string;
  items: ObjectId[];
}

const AutoGeneratedPlaylistSchema = new Schema<AutoGeneratedPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: [
      {
        type: Schema.Types.ObjectId,
        ref: 'Audio',
        required: true,
      },
    ],
  },
  {
    timestamps: true,
  }
);

const AutoGeneratedPlaylist =
  models.AutoGeneratedPlaylist ||
  model('AutoGeneratedPlaylist', AutoGeneratedPlaylistSchema);
export default AutoGeneratedPlaylist as Model<AutoGeneratedPlaylistDocument>;
